language: java
addons:
  sonarqube: true
#env:
 # global:
  #  - secure: ********* # defines SONAR_TOKEN=abcdef0123456789
script:
  # other script steps might be done before running the actual SonarQube analysis
  - sonar-scanner -Dsonar.login=e770ef00d13b6424c43910f5064a75b01de64fa1
