package modelos;

// Generated 08-dic-2011 13:53:39 by Hibernate Tools 3.4.0.CR1

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private String userdId;
	private String name;

	public Users() {
	}

	public Users(String userdId, String name) {
		this.userdId = userdId;
		this.name = name;
	}

	public String getUserdId() {
		return this.userdId;
	}

	public void setUserdId(String userdId) {
		this.userdId = userdId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
